#!/usr/bin/env python3
import argparse
from src.crypto.ed25519_utils import AetherCrypto
from src.consensus.bridge_node import node # Importamos el nodo que guarda cosas

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--msg", required=True)
    parser.add_argument("--key", required=True)
    parser.add_argument("--pub", required=True, help="Tu llave pública")
    
    args = parser.parse_args()
    
    # 1. Firmamos
    signature = AetherCrypto.sign_message(args.msg, args.key)
    
    # 2. Guardamos en el 'Bridge' (Persistencia)
    packet_id = node.save_packet(origin=args.pub, payload=args.msg, signature=signature)
    
    print(f"[✔] Mensaje #{packet_id} firmado y guardado en el silo local.")
    print(f"[*] Listo para transmisión física (Pendrive) o por radio.")

if __name__ == "__main__":
    main()